name: retrieve_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.15.0
  firebase_database: ^10.2.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  wakelock_plus: ^1.1.4
  geolocator: ^10.1.0
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
